# Generated by Django 4.2.11 on 2024-04-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_recipe_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instruction',
            new_name='instructions',
        ),
    ]
