# Generated by Django 4.2.11 on 2024-04-28 11:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='feat_img',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
