# Generated by Django 4.2.11 on 2024-04-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_recipelikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
